[build]
builder = "nixpacks"
buildCommand = """
  yarn install &&
  npx prisma generate &&
  yarn build
"""

[deploy]
startCommand = "npx prisma migrate deploy && yarn start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 100