[build]
builder = "nixpacks"
buildCommand = "yarn install && yarn prisma:generate && yarn prisma:migrate && yarn build"

[deploy]
startCommand = "yarn start:prod"
healthcheckPath = "/api"
healthcheckTimeout = 100